-- PASILLO DEL REY - MIGRACIÓN DE NOTIFICACIONES
-- Ejecutar DESPUÉS de supabase_schema.sql.
-- Zona horaria de avisos: America/Lima.

alter table public.profiles
  add column if not exists apoderado_nombre text,
  add column if not exists apoderado_whatsapp text,
  add column if not exists apoderado_email text,
  add column if not exists notificaciones_whatsapp boolean not null default true,
  add column if not exists notificaciones_email boolean not null default true;

create table if not exists public.notification_log (
  id bigint generated by default as identity primary key,
  subscription_id bigint not null references public.subscriptions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null check (channel in ('email','whatsapp')),
  days_before integer not null,
  destination text,
  status text not null default 'pending',
  provider_message_id text,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique(subscription_id, channel, days_before)
);

alter table public.notification_log enable row level security;

drop policy if exists "notification_log_self_select" on public.notification_log;
create policy "notification_log_self_select"
on public.notification_log
for select to authenticated
using (user_id = auth.uid());

drop policy if exists "profiles_self_update" on public.profiles;
create policy "profiles_self_update"
on public.profiles
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- Función de mantenimiento: marca suscripciones vencidas.
create or replace function public.mark_expired_subscriptions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  n integer;
begin
  update public.subscriptions
     set status = 'expired'
   where status = 'active'
     and expires_at is not null
     and expires_at <= now();
  get diagnostics n = row_count;
  return n;
end;
$$;

-- Vista útil para el panel/admin.
create or replace view public.subscription_status
with (security_invoker=true)
as
select
  s.id,
  s.user_id,
  s.status,
  s.starts_at,
  s.expires_at,
  greatest(0, floor(extract(epoch from (s.expires_at - now()))/86400))::integer as days_remaining
from public.subscriptions s;

-- Habilita pg_cron y pg_net desde SQL si están disponibles en tu proyecto.
create extension if not exists pg_cron;
create extension if not exists pg_net;

-- IMPORTANTE: este job solo marca vencimientos.
-- El envío de WhatsApp/correo se realiza mediante la Edge Function.
select cron.schedule(
  'pasillo-marcar-vencidos',
  '5 3 * * *',
  $$select public.mark_expired_subscriptions();$$
)
where not exists (
  select 1 from cron.job where jobname='pasillo-marcar-vencidos'
);

-- Los avisos se disparan con la Edge Function.
-- Configura el cron HTTP en Supabase después de guardar los secrets:
-- SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY.
-- Ejemplo (03:10 UTC = 22:10 del día anterior en Lima):
--
-- select cron.schedule(
--   'pasillo-notificar-vencimientos',
--   '10 3 * * *',
--   $$
--   select net.http_post(
--     url := 'https://sozopfatthuryfxmhiek.supabase.co/functions/v1/notify-expirations',
--     headers := jsonb_build_object(
--       'Content-Type','application/json',
--       'apikey','TU_PUBLISHABLE_KEY'
--     ),
--     body := jsonb_build_object('source','cron')
--   );
--   $$
-- );
