-- PASILLO DEL REY: cuentas, suscripciones, compras y biblioteca privada
-- Ejecuta este archivo completo en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  whatsapp text,
  created_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric(10,2) not null default 0,
  file_path text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'yape',
  provider_customer_id text,
  provider_subscription_id text unique,
  status text not null default 'pending' check (status in ('pending','active','expired','cancelled')),
  starts_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  provider text not null default 'yape',
  provider_payment_id text unique,
  amount numeric(10,2) not null,
  currency text not null default 'PEN',
  status text not null default 'pending',
  metadata jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.book_entitlements (
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  granted_at timestamptz not null default now(),
  primary key(user_id,book_id)
);

create or replace view public.library_access
with (security_invoker=true)
as
select
  be.user_id,
  b.id as book_id,
  b.title,
  b.description,
  b.file_path,
  s.status as subscription_status,
  s.expires_at
from public.book_entitlements be
join public.books b on b.id=be.book_id and b.active=true
left join lateral (
  select status, expires_at
  from public.subscriptions s0
  where s0.user_id=be.user_id
  order by s0.created_at desc
  limit 1
) s on true
where exists (
  select 1 from public.subscriptions sx
  where sx.user_id=be.user_id
    and sx.status='active'
    and (sx.expires_at is null or sx.expires_at > now())
);

alter table public.profiles enable row level security;
alter table public.books enable row level security;
alter table public.subscriptions enable row level security;
alter table public.payments enable row level security;
alter table public.book_entitlements enable row level security;

drop policy if exists "profiles_self_select" on public.profiles;
create policy "profiles_self_select" on public.profiles for select to authenticated using (id=auth.uid());

drop policy if exists "books_active_select" on public.books;
create policy "books_active_select" on public.books for select to authenticated using (active=true);

drop policy if exists "subscriptions_self_select" on public.subscriptions;
create policy "subscriptions_self_select" on public.subscriptions for select to authenticated using (user_id=auth.uid());

drop policy if exists "payments_self_select" on public.payments;
create policy "payments_self_select" on public.payments for select to authenticated using (user_id=auth.uid());

drop policy if exists "entitlements_self_select" on public.book_entitlements;
create policy "entitlements_self_select" on public.book_entitlements for select to authenticated using (user_id=auth.uid());

-- Libros de ejemplo: cambia file_path por los nombres reales de tus PDFs.
insert into public.books(title,description,price,file_path)
values
('Fundamentos del Ajedrez','Material de fundamentos y principios.','15.00','fundamentos.pdf'),
('Táctica y Combinaciones','Material de entrenamiento táctico.','20.00','tactica.pdf'),
('Preparación para Torneos','Material de preparación competitiva.','25.00','torneos.pdf')
on conflict (file_path) do nothing;

-- Perfil automático al crear una cuenta.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id) values(new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Bucket privado para PDFs.
insert into storage.buckets(id,name,public)
values ('libros','libros',false)
on conflict (id) do update set public=false;

-- El usuario no recibe acceso directo a storage: las descargas pasan por Edge Function.
